function axis = setFigure(axis)

set(axis, ...
    'Box'         , 'off'     , ...
    'XTick',[],'XTickLabel',[], ...
    'YTick',[],'YTickLabel',[], ...
    'Visible'     , 'off'        , ...
    'Color'       , 'w', ...
    'LineWidth'   , 1         );
set( axis                       , ...
    'FontName'   , 'Helvetica' );
