function hLegend = setLegends(hData, Legends)
hLegend = legend( ...
    [hData], ...
    Legends , ...
    'location', 'NorthEast' );
set([hLegend, gca]             , ...
    'FontSize'   , 20           );
set(hLegend, 'Interpreter', 'none');
end
