function hText = setText(text_, PosX, PosY)

hText   = text(PosX, PosY, ...
    text_, ...
    'HorizontalAlignment','Center');
set([hText], ...
    'FontName'   , 'Helvetica');
set([hText]  , ...
    'FontSize'   , 20          );
